<!DOCTYPE html>

<html>
<head>  <meta charset="utf-8"/>
    <meta name="descripion" content="html Project">
    <script src="https://kit.fontawesome.com/eb87e9f96b.js" crossorigin="anonymous"></script>
<title>Friends project</title


</head>
  

    <link rel="stylesheet" href="CSS.CSS">

    
    <style>

    </style>

<body align="center" background="" def="rtl" >

<header>
        <a href="#" class="Logo">7ORAS</a>
        
        <nav class="navigation">
        
        <a href="1"></a>
        <a href="https://www.facebook.com/profile.php?id=100010427855195" target="blank">Moaz</a>
        <a href="https://www.facebook.com/profile.php?id=100014362308743" target="blank">Tykmo</a>
        <a href="4">About us</a>
        
        
        
        
        
        
        
        </nav>
</section>
        
        
        </header></nav>


<!------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------>







<!-- ملحوظة دة الجذء المسئول عن الفديدو المعروض والصور-->

    





    

<section class="main">
<div>
<h2>Hello, I am 7ORAS <br><span>Developer </span></h2>
<h3>7ORAS</h3>
<a href="#" class="main-btn">View My Work</a>
<div class="social">

    <a href="#"><i class="fa-brands fa-facebook"></i></a>
    <a href="#"><i class="fa-brands fa-github"></i></a>
    <a href="https://discord.gg/fAYMJQCTU9" target="_blank"><i class="fa-brands fa-discord"></i></i></a>
    
   
    

<div>
    <h4><Details><Table border="1" bgcolor="burlywood" align="center" ></h4>
        <thead>
    
        </thead>
    
        <tbody align="center">
        <tr><th>Project By</th></tr>
    <font face="Brush Script MT"><tr bgcolor="aqua"><td>7ORAS</td></tr></font>
    <tr bgcolor="cornflowerblue"><td>Tykmo</td></tr>
    <tr bgcolor="teal"><td>Moaz</td></tr>
    
        </tbody>
     <tfoot>
    
     </tfoot>   
    
    
    
    
    
    </Table></Details>
</section>
<section class="projects" id="projects">
    <h2 class="title">Projects</h2>
    <div class="content">
        <div class="project-card">
            <div class="project-image">
                <img src="https://cdn.discordapp.com/attachments/930891243322490921/1023752037512523877/IMG_5196.png" />
            </div>
            <div class="project-info">
                <p class="project-category">Script Writing & Video Production</p>
                <strong class="project-title">
                    <span>Dr Moaz</span>
                    <a href="#" class="more-details">More details</a>
                </strong>
            </div>
        </div>
        <div class="project-card">
            <div class="project-image">
                <img src="https://scontent-mrs2-2.xx.fbcdn.net/v/t39.30808-6/277754210_1259465154542216_5459394283966534764_n.jpg?_nc_cat=108&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=gX82u5lcHlYAX_3rikn&_nc_ht=scontent-mrs2-2.xx&oh=00_AT80vrFHOM9VArH7_rpyIR4lWl2LbZy5bMmNWn0UsJrkDg&oe=635BF089" />
            </div>
            <div class="project-info">
                <p class="project-category">Script Writing & Video Production</p>
                <strong class="project-title">
                    <span>Tykmo</span>
                    <a href="#" class="more-details">More details</a>
                </strong>
            </div>
        </div>
        <div class="project-card">
            <div class="project-image">
                <img src="https://cdn.discordapp.com/attachments/931589169308913704/1023601970965131294/WhatsApp_Image_2022-09-23_at_23.48.08.jpeg" />
            </div>
            <div class="project-info">
                <p class="project-category">Script Writing & Video Production</p>
                <strong class="project-title">
                    <span>Gom3a</span>
                    <a href="#" class="more-details">More details</a>
                </strong>
            </div>
        </div>
        <div class="project-card">
            <div class="project-image">
                <img src="https://media.tenor.com/n3NPvU-gSRwAAAAS/phoenix-phoenix-valorant.gif" />
            </div>
            <div class="project-info">
                <p class="project-category">Script Writing & Video Production</p>
                <strong class="project-title">
                    <span>7ORAS</span>
                    <a href="#" class="more-details">More details</a>
                </strong>
            </div>
        </div>
        <div class="project-card">
            <div class="project-image">
                <img src="https://media.giphy.com/media/ZG4fyysTerYPBrEbeC/giphy.gif" />
            </div>
            <div class="project-info">
                <p class="project-category">Script Writing & Video Production</p>
                <strong class="project-title">
                    <span>WUW</span>
                    <a href="#" class="more-details">More details</a>
                </strong>
            </div>
        </div>
        <div class="project-card">
            <div class="project-image">
                <img src="https://media.giphy.com/media/m3N5PpxSyYyFICeSvb/giphy-downsized-large.gif" />
            </div>
            <div class="project-info">
                <p class="project-category">Script Writing & Video Production</p>
                <strong class="project-title">
                    <span>WUW</span>
                    <a href="#" class="more-details">More details</a>
                </strong>
            </div>
        </div>
        <div class="project-card">
            <div class="project-image">
                <img src="https://media.giphy.com/media/QdPy2EL9wr0GpMHD39/giphy.gif" />
            </div>
            <div class="project-info">
                <p class="project-category">Script Writing & Video Production</p>
                <strong class="project-title">
                    <span>BIG</span>
                    <a href="https://cheater.wiki/products/wikispoof/" class="more-details">download</a>
                </strong>
            </div>
        </div>
    </div>
</section>
</div>
</div>
<section class="videos" id="videos">
    <h2 class="title">Videos</h2>
    <div class="video-card">
        <Div class="project-video">
            <iframe width="560" height="315" src="https://www.youtube.com/embed/86awQt_ZNGo" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
           <inframe width="560" height="315" src=""></inframe>
           
        </Div>
    </div>
    <div class="video-card">
        <Div class="project-video">
            <blockquote class="tiktok-embed" cite="https://www.tiktok.com/@asaliraniii/video/7112087447944596741" data-video-id="7112087447944596741" style="max-width: 605px;min-width: 325px;" > <section> <a target="_blank" title="@asaliraniii" href="https://www.tiktok.com/@asaliraniii?refer=embed">@asaliraniii</a> I Love this Challenge @nurcinaleyna 💞<a title="fyfyfyfyfyfyfyfyfyfyfyfyfyfyfyfyfyfy" target="_blank" href="https://www.tiktok.com/tag/fyfyfyfyfyfyfyfyfyfyfyfyfyfyfyfyfyfy?refer=embed">#fyfyfyfyfyfyfyfyfyfyfyfyfyfyfyfyfyfy</a> <a title="viral" target="_blank" href="https://www.tiktok.com/tag/viral?refer=embed">#viral</a><a title="viral_video" target="_blank" href="https://www.tiktok.com/tag/viral_video?refer=embed">#viral_video</a><a title="sturdy" target="_blank" href="https://www.tiktok.com/tag/sturdy?refer=embed">#sturdy</a><a title="sturdyvibes" target="_blank" href="https://www.tiktok.com/tag/sturdyvibes?refer=embed">#sturdyvibes</a><a title="foryou" target="_blank" href="https://www.tiktok.com/tag/foryou?refer=embed">#foryou</a><a title="fyfy" target="_blank" href="https://www.tiktok.com/tag/fyfy?refer=embed">#fyfy</a><a title="fypシ" target="_blank" href="https://www.tiktok.com/tag/fyp%E3%82%B7?refer=embed">#fypシ</a><a title="dancing" target="_blank" href="https://www.tiktok.com/tag/dancing?refer=embed">#dancing</a><a title="dancetutorial" target="_blank" href="https://www.tiktok.com/tag/dancetutorial?refer=embed">#dancetutorial</a> <a title="dancer" target="_blank" href="https://www.tiktok.com/tag/dancer?refer=embed">#dancer</a><a title="trend2022" target="_blank" href="https://www.tiktok.com/tag/trend2022?refer=embed">#trend2022</a><a title="foryou" target="_blank" href="https://www.tiktok.com/tag/foryou?refer=embed">#foryou</a> <a title="asaliraniii" target="_blank" href="https://www.tiktok.com/tag/asaliraniii?refer=embed">#asaliraniii</a><a title="goodvibes" target="_blank" href="https://www.tiktok.com/tag/goodvibes?refer=embed">#goodvibes</a><a title="viralvideo" target="_blank" href="https://www.tiktok.com/tag/viralvideo?refer=embed">#viralvideo</a><a title="fypシ" target="_blank" href="https://www.tiktok.com/tag/fyp%E3%82%B7?refer=embed">#fypシ</a> <a target="_blank" title="♬ Nooran Sisters DRILL REMIX Prod. Philemon - philemon454🥷🏽🌐" href="https://www.tiktok.com/music/Nooran-Sisters-DRILL-REMIX-Prod-Philemon-7098756819988237062?refer=embed">♬ Nooran Sisters DRILL REMIX Prod. Philemon - philemon454🥷🏽🌐</a> </section> </blockquote> <script async src="https://www.tiktok.com/embed.js"></script>
            <
           
        </Div>
    </div>

    

   
    
        
        
 



<










</section>

<section class="cards contact" id="contact">
    <h2 class="title">Connect with us</h2>
    <div class="content">
        <div class="card">
            <div class="icon">
                <i class="fas fa-phone"></i>
            </div>
            <div class="info">
                <h3>Phone</h3>
                <p>+01024578495</p>
            </div>
        </div>
        <div class="card">
            <div class="icon">
                <i class="fas fa-envelope"></i>
            </div>
            <div class="info">
                <h3>Email</h3>
                <p>7ORAS88@gmail.com</p>
            </div>
        </div>
    </div>
    <footer class="footer">
        <p class="footer-title">Copyrights @ <span>7ORAS TM</span></p>
        <div class="social-icons">
            <a href="#"><i class="fab fa-linkedin"></i></a>
            <a href="#"><i class="fab fa-twitter"></i></a>
            <a href="#"><i class="fab fa-instagram"></i></a>
            <a href="#"><i class="fab fa-youtube"></i></a>
        </div>
    </footer>

</body>
</html>


